import '../src/styles/theme.css';
import '../src/styles/page.css';
import ErrorBoundary from '../src/ErrorBoundary';
import Menu from '../src/components/Menu';
import PageNarrator from '../src/components/PageNarrator';
import TopNav from '../src/components/TopNav';
import SpxHeatmap from '../src/components/SpxHeatmap';

// SPX Heatmap page. An equal-size GICS-sector grid of the top ~250
// single-name stocks by US options volume, colored by the most-recent
// session's percent change from previous close. Equal-size tiles are
// a deliberate departure from the conventional finviz / TradingView
// market-cap-weighted treemap: when MAG7 + a few mega-caps command a
// third of the visual, the other ~480 names compete for the
// remaining two-thirds and most of them aren't legible. Equal-size
// tiles give every name in the universe equal visual attention — the
// right call for an audience of vol traders who care about the names
// they actually trade, not the names that happen to be the largest
// by float-adjusted market cap.
//
// Data lineage:
//   tickers + sectors:  Barchart "stocks screener" CSV dropped at
//                       C:\sheets\, joined with GICS sectors via the
//                       GitHub datasets/s-and-p-500-companies CSV
//                       (SP500 names) plus a manually-maintained
//                       MANUAL_SECTORS map in the generator script
//                       for the ~90 non-SP500 names that show up on
//                       the options-active board (BTC miners, recent
//                       IPOs, ADRs, space / quantum / AI single
//                       names). Regenerated by
//                       scripts/backfill/options-volume-roster.mjs.
//   prices:             Massive grouped daily bars, two HTTP calls
//                       to fetch the most-recent two trading-day
//                       sessions, with ThetaData EOD via Supabase
//                       as a graceful fallback to 11 sector ETFs
//                       if Massive returns 401/403/timeout.
//
// See netlify/functions/heatmap.mjs for the join logic and
// src/components/SpxHeatmap.jsx for the equal-size grid renderer.
export default function App() {
  return (
    <div className="app-shell page-shell heatmap-shell">
      <header className="page-header">
        <div className="page-brand">
          <span
            className="page-badge"
            title="Heatmap · top by options volume, equal size, % change"
          >
            <span className="page-badge__desktop-text">Heatmap</span>
            <span className="page-badge__mobile-text">Heatmap</span>
          </span>
        </div>
        <TopNav />
        <a
          href="/"
          className="page-home-button page-home-button--inline page-home-button--split"
          aria-label="Return Home"
        >
          <span className="page-home-button__desktop-text">Home</span>
          <span className="page-home-button__mobile-text">Home</span>
        </a>
        <Menu />
      </header>

      <ErrorBoundary><PageNarrator page="/heatmap/" /></ErrorBoundary>

      <section className="page-slot heatmap-slot">
        <ErrorBoundary><SpxHeatmap /></ErrorBoundary>
      </section>

      <div className="card" style={{ padding: '1.1rem 1.25rem', margin: '1.25rem 0' }}>
        <div
          style={{
            fontFamily: "Calibri, 'Segoe UI', system-ui, sans-serif",
            fontSize: '0.7rem',
            letterSpacing: '0.14em',
            textTransform: 'uppercase',
            color: 'var(--text-secondary)',
            marginBottom: '0.45rem',
          }}
        >
          what this page measures
        </div>
        <div style={{ color: 'var(--text-secondary)', lineHeight: 1.65, fontSize: '0.95rem' }}>
          <p style={{ margin: '0 0 0.7rem' }}>
            <strong style={{ color: 'var(--text-primary)' }}>The Grid.</strong>{' '}
            The <strong style={{ color: 'var(--text-primary)' }}>top ~250 single-name stocks by
            US options volume</strong>, rendered as{' '}
            <strong style={{ color: 'var(--text-primary)' }}>equal-size tiles</strong> arranged
            into eleven GICS sector bands. Each tile is colored by the most-recent session's
            percent change from previous close:{' '}
            <strong style={{ color: 'var(--accent-coral)' }}>strong red below -2%</strong>,
            neutral within ±0.25%,{' '}
            <strong style={{ color: 'var(--accent-green)' }}>strong green above +2%</strong>, with
            linear ramps between. Hover any tile for company name, last price, previous close, and
            options-volume rank.
          </p>
          <p style={{ margin: '0 0 0.7rem' }}>
            <strong style={{ color: 'var(--text-primary)' }}>Why equal-size?</strong>{' '}
            A deliberate departure from the conventional{' '}
            <strong style={{ color: 'var(--text-primary)' }}>market-cap-weighted treemap</strong>.
            When <strong style={{ color: 'var(--text-primary)' }}>MAG7 + a handful of mega-caps
            command a third of the visual</strong> (NVDA + AAPL + MSFT + AMZN + AVGO + GOOGL/GOOG
            + META ≈ 32% of SP500 weight), the other ~480 names compete for the remaining
            two-thirds and most are illegible.
          </p>
          <p style={{ margin: 0 }}>
            Equal-size tiles give <strong style={{ color: 'var(--text-primary)' }}>every name
            equal visual attention</strong>. The right call for an audience that cares about the
            names they actually trade, not the names that happen to be the largest by
            float-adjusted market cap. The universe shrinks from ~503 SP500 members to the{' '}
            <strong style={{ color: 'var(--text-primary)' }}>top ~250 single names by options
            volume</strong> in exchange.
          </p>
        </div>
      </div>

      <footer className="page-footer">
        <span className="page-footer-line">
          AI Gamma · SPX Heatmap · top by options volume, equal size · v0.2.0
        </span>
        <a href="/disclaimer/" className="page-footer-disclaimer">Disclaimer</a>
        <a href="/" className="page-footer-home">Return Home</a>
        <a href="https://about.aigamma.com/" className="page-footer-about">Created by Eric Allione</a>
      </footer>
    </div>
  );
}
